### PR TITLE
Fix #5

### LINKED ISSUE #5: Jerry Box type extraction is buggy
**Describe the bug**
Detecting the jerry box type is not perfect, yet.
Sometimes on rightcllick to open it does not detect it
and then the old box type or at the start none at all gets written down.

**Desktop:**
 - OS: Windows
 - Version: 10
 - Minecraft Version: Forge 1.8.9

### PR DESCRIPTION
**Pull request by taj-ny**
This hopefully fixes #5. It happens when you are only holding one item and is caused by MouseEvent being fired too late, after it has been placed. Changing it to PlayerInteractEvent seems to fix this issue, however I'm currently banned from Hypixel so I couldn't test it there.

### CODE REVIEW

**Comment by doej1367** [comment]
```
PlayerInteractEvent is fired when a player interacts in some way. 
This event is fired whenever a player interacts inMinecraft#rightClickMouse(),NetHandlerPlayServer#processPlayerBlockPlacement(C08PacketPlayerBlockPlacement),ItemInWorldManager#activateBlockOrUseItem(EntityPlayer, World, ItemStack, int, int, int, int, float, float, float),ItemInWorldManager#onBlockClicked(int, int, int, int). 
```

looks like it should work - let me quickly try it out

Also: I am pleasently surprised to see someone responding that quickly - thank you for that :)

**Comment by doej1367** [comment]
This now does not work on air left click.

I guess the cleanest version would be to take the information from the chest gui that opens after the click.

grafik

**Comment by taj-ny** [comment]
Maybe this will work? I also moved stuff related to jerry boxes from HypixelEventHandler to JerryBoxEventHandler to make it easier.

**Comment by doej1367** [comment]
Looks good to me and I will merge it later.

A few tips for the future and notes:
- always create and switch to a new branch after forking a project - makes merging easier
- moving the ChatEvent handling from the HypixelEventHandler might look like things belonging together are in one place, but now there is duplicate code with parsing the chat message... i'll probably change that back later

Keep up the good work :)

(just saw your chat filter mod - might try that one out later...)

**Comment by doej1367** [comment]
Works and published!

**Pull request merged**
